const STATES = [
  {
    id: 0,
    abb: "AN",
    name: "Andaman and Nicobar Islands",
    state: "andaman-and-nicobar",
  },
  {
    id: 1,
    abb: "AP",
    name: "Andhra Pradesh",
    state: "andhra-pradesh",
  },
  {
    id: 2,
    abb: "AR",
    name: "Arunachal Pradesh",
    state: "arunachal-pradesh",
  },
  {
    id: 3,
    abb: "AS",
    name: "Assam",
    state: "assam",
  },
  {
    id: 4,
    abb: "BR",
    name: "Bihar",
    state: "bihar",
  },
  {
    id: 5,
    abb: "CG",
    name: "Chandigarh",
    state: "chandigarh",
  },
  {
    id: 6,
    abb: "CH",
    name: "Chhattisgarh",
    state: "chattishgarh",
  },
  {
    id: 7,
    abb: "DH",
    name: "Dadra and Nagar Haveli",
    state: "dadra-and-nagar",
  },
  {
    id: 8,
    abb: "DD",
    name: "Daman and Diu",
    state: "daman-and-diu",
  },
  {
    id: 9,
    abb: "DL",
    name: "Delhi",
    state: "delhi",
  },
  {
    id: 10,
    abb: "GA",
    name: "Goa",
    state: "goa",
  },
  {
    id: 11,
    abb: "GJ",
    name: "Gujarat",
    state: "gujrat",
  },
  {
    id: 12,
    abb: "HR",
    name: "Haryana",
    state: "haryana",
  },
  {
    id: 13,
    abb: "HP",
    name: "Himachal Pradesh",
    state: "himachal-pradesh",
  },
  {
    id: 14,
    abb: "JK",
    name: "Jammu and Kashmir",
    state: "jammu-and-kashmir",
  },
  {
    id: 15,
    abb: "JH",
    name: "Jharkhand",
    state: "jharkhand",
  },
  {
    id: 16,
    abb: "KA",
    name: "Karnataka",
    state: "karnataka",
  },
  {
    id: 17,
    abb: "KL",
    name: "Kerala",
    state: "kerala",
  },
  {
    id: 18,
    abb: "LD",
    name: "Lakshadweep",
    state: "lakshadweep",
  },
  {
    id: 19,
    abb: "MP",
    name: "Madhya Pradesh",
    state: "madhya-pradesh",
  },
  {
    id: 20,
    abb: "MH",
    name: "Maharashtra",
    state: "maharashtra",
  },
  {
    id: 21,
    abb: "MN",
    name: "Manipur",
    state: "manipur",
  },
  {
    id: 22,
    abb: "ML",
    name: "Meghalaya",
    state: "meghalaya",
  },
  {
    id: 23,
    abb: "MZ",
    name: "Mizoram",
    state: "mizoram",
  },
  {
    id: 24,
    abb: "NL",
    name: "Nagaland",
    state: "nagaland",
  },
  {
    id: 25,
    abb: "OR",
    name: "Odisha",
    state: "odhisha",
  },
  {
    id: 26,
    abb: "PY",
    name: "Puducherry",
    state: "puducherry",
  },
  {
    id: 27,
    abb: "PB",
    name: "Punjab",
    state: "punjab",
  },
  {
    id: 28,
    abb: "RJ",
    name: "Rajasthan",
    state: "rajasthan",
  },
  {
    id: 29,
    abb: "SK",
    name: "Sikkim",
    state: "sikkim",
  },
  {
    id: 30,
    abb: "TN",
    name: "Tamil Nadu",
    state: "tamil-nadu",
  },
  {
    id: 31,
    abb: "TS",
    name: "Telangana",
    state: "telangana",
  },
  {
    id: 32,
    abb: "TR",
    name: "Tripura",
    state: "tripura",
  },
  {
    id: 33,
    abb: "UK",
    name: "Uttar Pradesh",
    state: "uttar-pradesh",
  },
  {
    id: 34,
    abb: "UP",
    name: "Uttarakhand",
    state: "uttarakhand",
  },
  {
    id: 35,
    abb: "WB",
    name: "West Bengal",
    state: "west-bengal",
  },
];

export default STATES;
