const CONSTANTS_MESSAGES = {
  USER_EXISTS: "User already exists",
  USER_INACTIVE: "User inactive. Contact OPD Sure for reactivation",
  INTERNAL_SERVER_ERROR: "Something went wrong. Please try again",
  SUCCESS: "API executed successfully",
  USER_NOT_FOUND: "User not found in database ",
  SPECIALIZATION_NOT_FOUND: "Specialization does not exists in database ",
  ID_NOT_FOUND: "Id not found in database",
  APPLICATION_UNDER_JOB: "There is application under job. It can't be deleted",
  BLOG_NOT_FOUND: "No blog found",
  MEDIA_NOT_FOUND: "Media article not found",
  EVENT_NOT_FOUND: "Event article not found",
  POST_NOT_FOUND: "Post article not found",
  JOB_NOT_FOUND: "Job not found",
  ALREADY_APPLIED: "You have already applied for job.",
  REVIEW_NOT_FOUND: "No review found",
  CORPORATE_NOT_FOUND: "Corporate not found in database",
  WRONG_PASSWORD: "Wrong password entered",
  EMAIL_EXISTS: "Email already registered",
  MOBILE_EXISTS: "Mobile already registered",
  HR_FOR_COMPANT_EXISTS: "HR already registered for company",
  COUPON_CODE_EXISTS: "Coupon code already exists",
  PERMISSION_UPDATE_FAILED: "Failed to update permissions",
  BULK_UPLOAD_FAILED: "Bulk Upload failed",
  DOC_REGNO_EXISTS: "Doctor's registration number already exists",
  NAME_EXISTS: "Name already exists",
  CHECKUP_CODE_EXISTS: "Health Checkup code already exists",
  CHECKUP_PLAN_NOT_EXISTS: "Health Checkup plain does not exists",
  CANNOT_DOWNGRADE_PLAN: "Plan cannot be downgraded",
  INVALID_TOKEN: "Invalid jwt token",
  ADMIN_NOT_FOUND: "Admin not found in database",
  INVALID_PASS_REQ: "Invalid request to reset password",
  ADMIN_INACTIVE: "Admin is inactive",
  MANAGEMENT_USER_NOT_FOUND: "Management user not found in database",
  MANAGEMENT_USER_HAS_ASSIGNED_CLAIMS: "Management user has assigned claims",
  MANAGEMENT_USER_INACTIVE: "Management user is inactive",
  INVALID_PASSWORD: "Password must contains 1 Uppercase 1 Number and 1 Special Character with length at least 8",
  UNAUTHORIZED: "Not authorized.",
  TOKEN_NOT_FOUND: "Token not found",
  INVALID_OTP: "Invalid OTP",
  OTP_EXPIRED: "OTP is expired.",
  OLD_NEW_PASSWORD_ERROR: "New password can't be same as old password",
  MEMBER_NOT_FOUND: "Family member not found",
  FREE_TEST_ALREADY_AVAILED: "You have already availed free test for the member",
  MEMBER_DELETE_ERROR: "Approval request is under process, can't delete member",
  FAILED_TO_UPDATE_CLAIM_STATUS: "Failed to update claim status",
  CLAIM_ALREADY_APPROVED: "Claim already approved",
  ACTION_ALREADY_TAKEN: "Action on claim already taken",
  FAMILY_MEMBER_NOT_FOUND: "User not found",
  PLAN_EXPIRED_CANNOT_RAISE_CLAIM: "Your plan is expired. Cannot raise new claim.",
  ACTION_ALREADY_TAKEN: "Action already taken",
  CANNOT_ADD_MAIN_MEMBER: "Account owner cannot be added",
  CANNOT_EDIT_MAIN_MEMBER: "Account owner status cannot be changed",
  PLAN_EXPIRED: "Account owner status cannot be changed",
  PLAN_EXPIRED_CANNOT_RENEW: "Plan is already expired cannot renew form profile",
  PAID_MEMBER_LIST_FULL: "Max limit for paid members reached for subscribed plan",
  FAMILY_MEMBER_UPDATE_PENDING: "Family member update pending",
  DISPUTE_ALREADY_RAISED: "Dispute already raised on claim",
  DISPUTE_CANNOT_BE_RAISED: "Dispute cannot be raised as claim is under process",
  CLAIM_ALREADY_REJECTED: "Claim already rejected",
  INVALID_COUPON_CODE: "Invalid coupon code",
  NOT_VALID_FOR_RETAIL_USERS: "Coupon code invalid for retail users",
  NOT_VALID_FOR_CORPORATE_USERS: "Coupon code invalid for corporate users",
  NOT_VALID_FOR_THIS_CORPORATE: "Coupon code invalid for your company",
  EXCEEDED_MAX_ALLOWED_USAGE: "Exceeded maximum allowed usage",
  COUPON_ALREADY_USED: "Coupon code already used",
  EXPIRED_COUPON_CODE: "Validity expired for coupon code",
  PLAN_EXPIRED_UPGRADE: "Plan cannot be upgraded. Plan already expired.",
  MEMBER_DELETE_ERROR: "Approval request is under process, can't delete member",
  MEMBER_CANNOT_DELETE_ERROR: "Member can not be delete",
  CLAIM_NOT_FOUND: "Claim not found.",
  FORGOT_PASSWORD: "Link sent on your mail",
  CONFLICT_SELF: "Main user can not be repeated",
  NEGATIVE_AMOUNT: "Amount cannot be negative",
  MEMBER_LIMIT: "Family members can't be more than 10",
  PLAN_NOT_FOUND: "Plan doesn't exist.",
  EMAIL_TEMPLATE_NOT_FOUND : "Email template not found",
  CLAIM_NOT_APPROVED: "Claim not appoved from finance",
  DISPUTE_NOT_APPROVED: "Disputed claim not appoved from finance",
  VERIFIER_NOT_FOUND: "Verifier not found.",
  VERIFIER_NOT_TRANSFERABLE: "Only pending and clarification claims can be transfered",
  INSUFFICIENT_BALANCE: "Insufficient wallet balance",
  CANNOT_DELETE_USER_CLAIM_RAISED: " Cannot delete user as  claim is already raised by user.",
  REFER_USER_EXIST: "Referal already exist",
  SELF_REFER: "Can't refer itself.",
  FAILED_DELETE_IMAGE: "Failed to delete image.",
  CANNOT_DELETE_ALL_IMAGES: "All images cannot be deleted.",
  MAXIMUM_IMAGE_COUNT_REACHED: "Maximum 5 images can be added",
  APPOINTEMNT_ALREADY_TAKEN: "Appointment already scheduled",
  API_CLIENT_NOT_FOUND: "API client not found",
  API_CLIENT_EXISTS: "API client with this name already exists",
  API_KEY_NOT_FOUND: "API key not found",
  API_KEY_REVOKED: "API key is already revoked",
  API_KEY_EXPIRED: "API key has expired",
  INVALID_API_KEY: "Invalid API key",
  INVALID_API_KEY_FORMAT: "Invalid API key format",
  MISSING_API_KEY: "Missing X-API-KEY header",
  API_CLIENT_INACTIVE: "API client is inactive",
  RATE_LIMIT_EXCEEDED: "Rate limit exceeded. Please try again later.",
  RATE_LIMIT_UNAVAILABLE: "Rate limiting service unavailable. Please try again later.",
}

module.exports = CONSTANTS_MESSAGES;
