const version = import.meta.env.VITE_API_VERSION;
const baseUrl = import.meta.env.VITE_API_BASE_URL;
const razorpay_key = import.meta.env.VITE_API_RAZORPAY_KEY_ID

export const CONFIG_OBJ = {
  headers: {
    "Content-Type": "application/json",
    "Authorization": "Bearer " + localStorage.getItem("token")
  }
};
export const CONFIG_OBJ_DOC = {
  headers: {
    "Content-Type": "multipart/form-data", // Set the content type for file uploads
    "Authorization": "Bearer " + localStorage.getItem("token")
  }
};
const config = {
  razorpay_key: razorpay_key,
  ApiBaseUrl: baseUrl,
  AdminLogin: `/api/${version}/admin/login`,
  AdminSignup: `/api/${version}/admin/signup`,
  AdminUserLogout: `/api/${version}/admin/logout`,
  ManagementUserLogin: `/api/${version}/management/login`,
  ManagementUserLogout: `/api/${version}/management/logout`,
  GetAllDesig: `/api/${version}/admin/designation/`,
  EditDesig: `/api/${version}/admin/designation/`,
  DeleteDesig: `/api/${version}/admin/designation/`,
  AddDesig: `/api/${version}/admin/designation/`,
  GetAllCorpo: `/api/${version}/admin/corporation/`,
  GetAllCorporation: `/api/${version}/admin/allcorporation/`,
  EditCorpo: `/api/${version}/admin/corporation/`,
  DeleteCorpo: `/api/${version}/admin/corporation/`,
  AddCorpo: `/api/${version}/admin/corporation/`,
  GetAllPlan: `/api/${version}/public/plan/`,
  EditPlan: `/api/${version}/admin/plan/`,
  DeletePlan: `/api/${version}/admin/plan/`,
  AddPlan: `/api/${version}/admin/plan/`,
  EditHealthCheckupPlan: `/api/${version}/admin/health-checkup-plans/`,
  DeleteHealthCheckupPlan: `/api/${version}/admin/health-checkup-plans/`,
  AddHealthCheckupPlan: `/api/${version}/admin/health-checkup-plans/`,
  GetAllHealthCheckupPlan: `/api/${version}/public/get-health-checkup-plans/`,
  GetAllSpecialization: `/api/${version}/public/specialization/`,
  EditSpecialization: `/api/${version}/admin/specialization/`,
  DeleteSpecialization: `/api/${version}/admin/specialization/`,
  AddSpecialization: `/api/${version}/admin/specialization/`,
  GetAllReferedUsers: `/api/${version}/admin/refered-users`,
  ReferedUsersAction: `/api/${version}/admin/refered-users/`,
  GetAllUpdatedUsers: `/api/${version}/admin/update-members`,
  ApproveUpdatedUser: `/api/${version}/admin/update-members/`,
  DeleteUpdatedUser: `/api/${version}/admin/update-members/`,
  GetAllFamilyMembers: `/api/${version}/admin/get-family-details/`,
  EditFamilyMembers: `/api/${version}/admin/edit-family-members/`,
  AddFamilyMembersAdmin: `/api/${version}/admin/add-family-members/`,
  EditFamilyMembersAdmin: `/api/${version}/admin/edit-family-members-details/`,
  GetAllCouponUsages: `/api/${version}/admin/coupon-usages/`,
  GetDiscountAggregation: `/api/${version}/admin/aggregation/`,
  AddBlog: `/api/${version}/admin/blog/`,
  EditBlog: `/api/${version}/admin/blog/`,
  DeleteBlog: `/api/${version}/admin/blog/`,
  DeleteBlogImage: `/api/${version}/admin/blog-image/`,
  AddGoogleReview: `/api/${version}/admin/google-review/`,
  EditGoogleReview: `/api/${version}/admin/google-review/`,
  DeleteGoogleReview: `/api/${version}/admin/google-review/`,
  AddMedia: `/api/${version}/admin/media/`,
  EditMedia: `/api/${version}/admin/media/`,
  DeleteMedia: `/api/${version}/admin/media/`,
  DeleteMediaImage: `/api/${version}/admin/media-image/`,
  DeleteMediaIcon: `/api/${version}/admin/media-icon-image/`,
  AddEvent: `/api/${version}/admin/event/`,
  EditEvent: `/api/${version}/admin/event/`,
  DeleteEvent: `/api/${version}/admin/event/`,
  DeleteEventImage: `/api/${version}/admin/event-image/`,
  AddLinkedinPost: `/api/${version}/admin/linkedin/`,
  EditLinkedinPost: `/api/${version}/admin/linkedin/`,
  DeleteLinkedinPost: `/api/${version}/admin/linkedin/`,
  AddJob: `/api/${version}/admin/job/`,
  EditJob: `/api/${version}/admin/job/`,
  DeleteJob: `/api/${version}/admin/job/`,
  GetJobApplication: `/api/${version}/admin/job-application/`,



  GetAllCorpoHR: `/api/${version}/admin/corporateHr/`,
  EditCorpoHR: `/api/${version}/admin/corporateHr/`,
  EditCorpoHRPass: `/api/${version}/admin/corporateHr/password/`,
  DeleteCorpoHR: `/api/${version}/admin/corporateHr/`,
  AddCorpoHR: `/api/${version}/admin/corporateHr/`,
  GetPurchasedHealthCheckupsAdmin: `/api/${version}/admin/get-purchased-healthcheckups/`,
  EditPurchasedHealthCheckupsAdmin: `/api/${version}/admin/edit-purchased-healthcheckups/`,
  
  GetPurchasedHealthPlan : `/api/${version}/user/get-purchased-health-plan`,
  CreateOrder: `/api/${version}/user/create-orders`,
  CreatePlanUpgradeOrder: `/api/${version}/user/create-plan-upgrade-orders/`,
  CreatePlanRenewOrder: `/api/${version}/user/create-plan-renew-orders/`,
  VerifyPayment: `/api/${version}/user/verify-payment`,
  VerifyPlanUpgradePayment: `/api/${version}/user/verify-plan-upgrade-payment`,
  VerifyPlanRenewPayment: `/api/${version}/user/verify-plan-renew-payment`,
  ForgotPassword: `/api/${version}/admin/forgotpassword`,
  UserLogin: `/api/${version}/user/login`,
  UserSignupOTP: `/api/${version}/user/signup-otp`,
  UserLogininOTP: `/api/${version}/user/login-otp`,
  VerifySignupOTP: `/api/${version}/user/verify-signup-otp`,
  UserSignup: `/api/${version}/user/signup`,
  UserLogout: `/api/${version}/user/logout`,
  GetProfile: `/api/${version}/user/get-profile`,
  GetSubscribedPlan: `/api/${version}/user/get-subscribed-plan`,
  UpdateProfile : `/api/${version}/user/update-profile`,
  GetMembers: `/api/${version}/user/get-members`,
  AddMember: `/api/${version}/user/add-member`,
  EditMember: `/api/${version}/user/request-update-member`,
  DeleteMember: `/api/${version}/user/delete-member?id=`,
  AddClaim : `/api/${version}/user/add-claim`,
  GetClaimableAmount : `/api/${version}/user/get-claimable-amount/`,
  EditClaim : `/api/${version}/user/edit-claim/`,
  GetAllClaims : `/api/${version}/user/get-claims`,
  GetClaims : `/api/${version}/user/get-claim-details?id=`,
  GetAllDisputedClaims : `/api/${version}/user/get-disputed-claims`,
  GetDisputedClaim : `/api/${version}/user/get-disputed-claim-details/`,
  RaiseClaimDispute : `/api/${version}/user/claim-dispute/`,
  UploadClaim : `/api/${version}/user/upload-file`,
  AddHealthCheckUp : `/api/${version}/user/add-health-checkup`,
  GetHealthCheckUp : `/api/${version}/user/get-health-checkups`,
  GetAllHealthCheckUp : `/api/${version}/management/get-health-checkups`,
  GetPlanPrice: `/api/${version}/user/get-plan-price-details`,
  GetPlanUpgradePrice: `/api/${version}/user/get-upgrade-plan-price-details`,
  GetPlanRenewPrice: `/api/${version}/user/get-renew-plan-price-details`,
  ReferNewUser: `/api/${version}/user/refer`,
  GetUpgradePlan: `/api/${version}/user/upgrade-plan`,
  GetTransactions: `/api/${version}/user/get-transactions`,
  ResetUserPass: `/api/${version}/user/resetpassword`,
  GetQueuedPlan: `/api/${version}/user/get-queued-plans`,
  GetRequestedMember: `/api/${version}/user/get-requested-members`,
  GetUserNotifications: `/api/${version}/user/notifications/`,
  DeleteUserNotification: `/api/${version}/user/notification/`,
  GetReferedUsersUser: `/api/${version}/user/refered-users`, 
  GetMfineRedirectData: `/api/${version}/user/mfine`,
  GetFreeHealtTests: `/api/${version}/user/get-free-health-tests`,
  GetFreeHealtTestsAdmin: `/api/${version}/admin/get-health-checkups`,
  GetPurchasedHealthCheckups:`/api/${version}/user/get-purchased-healtchekup-plans`,
  FreeHealtTestsActionAdmin: `/api/${version}/admin/health-checkups-action`,
  UpdatePassword: `/api/${version}/admin/updatepassword`,
  SendTestCollectionDetails: `/api/${version}/user/collection-details`,
  
  GetClaimsManagement : `/api/${version}/management/get-claims`,
  GetClaimsDetailsManagement : `/api/${version}/management/get-claim-details?id=`,
  UpdateClaimManagement : `/api/${version}/management/update-claim/`,
  GetManagentUserProfile : `/api/${version}/management/get-profile/`,
  GetAllDisputedClaimsManagement : `/api/${version}/management/get-disputed-claims`,
  GetDisputedClaimManagement : `/api/${version}/management/get-disputed-claim-details/`,
  UpdateDisputeClaimManagement : `/api/${version}/management/claim-dispute/`,
  PayClaimAmount: `/api/${version}/management/pay-claim-amount`,
  GetVerifierList:`/api/${version}/management/get-verifiers`,
  TransferClaim: `/api/${version}/management/transfer-claim-verifier/`,
  GetManagementNotifications: `/api/${version}/management/notifications/`,
  DeleteManagementNotification: `/api/${version}/management/notification/`,
  ForgotPasswordManag: `/api/${version}/management/forgotpassword`,
  ForgotPasswordManagDetails: `/api/${version}/management/forgotpassword/details`,
  GetClaimsMan: `/api/${version}/management/get-allclaims`,
  GetRegisteredUsers: `/api/${version}/management/get-registered-usersbyemply`,
  GetRegisteredUsersbyempl: `/api/${version}/management/getusersbyemply`,
  GetContactUsRetailbyempl: `/api/${version}/management/contact-us-retailbyemply/`,
  GetContactUsRetailListbyempl: `/api/${version}/management/contact-us-retail-listbyemply/`,
  GetContactUsCorporatebyempl: `/api/${version}/management/contact-us-corporatesbyemply/`,
  GetContactUsCorporateListbyempl: `/api/${version}/management/contact-us-corporates-listbyemply/`,
  GetContactUsEmailbyempl: `/api/${version}/management/contact-us-emailsbyemply/`,


  GetAllTest: `/api/${version}/admin/test/`,
  EditTest: `/api/${version}/admin/test/`,
  DeleteTest: `/api/${version}/admin/test/`,
  AddTest: `/api/${version}/admin/test/`,
  GetAllSettings: `/api/${version}/admin/settings/`,
  EditSettings: `/api/${version}/admin/settings/`,
  GetClaimsAdmin: `/api/${version}/admin/get-claims`,
  GetClaimsAdminDetails : `/api/${version}/admin/get-claim-details?id=`,
  GetRegisteredUsersAdmin: `/api/${version}/admin/get-registered-users`,
  DeleteRegisteredUsers: `/api/${version}/admin/deleteregisteredusers`,
  GetUsersAdmin: `/api/${version}/admin/getusers`,
  GetContactUsRetailAdmin: `/api/${version}/admin/contact-us-retail/`,
  GetContactUsRetailAdminList: `/api/${version}/admin/contact-us-retail-list/`,
  GetContactUsCorporateAdmin: `/api/${version}/admin/contact-us-corporates/`,
  GetContactUsCorporateAdminList: `/api/${version}/admin/contact-us-corporates-list/`,
  GetContactUsEmailAdmin: `/api/${version}/admin/contact-us-emails/`,
  GetAdminNotifications: `/api/${version}/admin/notifications/`,
  DeleteAdminNotification: `/api/${version}/admin/notification/`,
  AdminUploadFiles : `/api/${version}/admin/upload-file`,
  GetAppliedJob : `/api/${version}/admin/job-application`,
  ForgotPasswordAdmin: `/api/${version}/admin/forgotpassword`,
  ForgotPasswordAdminDetails: `/api/${version}/admin/forgotpassword/details`,
  HealtCheckupPlansActionAdmin: `/api/${version}/admin/purchased-health-checkup-plans-action`,

  GetStateList: `/api/${version}/public/get-states`,
  GetRelationList : `/api/${version}/public/get-relations`,
  GetTestList: `/api/${version}/public/get-health-tests`,
  GetFileSize: `/api/${version}/public/get-file-size`,
  GetPlanData : `/api/${version}/public/plan`,
  GetTermsAndCondition : `/api/${version}/public/get-terms-and-condition`,
  GetAllHealthPlanData: `/api/${version}/public/get-health-checkup-plans`,
  RegisterDoctor:`/api/${version}/public/register-doctor`,
  GetAllBlogs: `/api/${version}/public/blogs`,
  GetBlog: `/api/${version}/public/blog`,
  GetAllGoogleReviews: `/api/${version}/public/google-reviews/`,
  GetGoogleReview: `/api/${version}/public/google-review/`,
  GetAllMedias: `/api/${version}/public/medias`,
  GetMedia: `/api/${version}/public/media`,
  GetAllEvents: `/api/${version}/public/events`,
  GetEvent: `/api/${version}/public/event/`,
  GetAllLinkedinPosts: `/api/${version}/public/linkedin`,
  GetLinkedinPost: `/api/${version}/public/linkedin/`,
  GetAllJobOpenings: `/api/${version}/public/jobs`,
  PostJobApplication : `/api/${version}/public/job-application`,
  UploadResume: `/api/${version}/public/upload-file`,
  CurrentTime: `/api/${version}/public/current-time`,

  GetJobs: `/api/${version}/public/jobs/`,
  ApplyJob: `/api/${version}/public/job-application/`,  

  GetEmailTemplate: `/api/${version}/admin/email-settings`,
  UpdateEmailTemplate: `/api/${version}/admin/email-settings/`,
  BulkUpload: `/api/${version}/admin/corpoEmp/bulk`,
  RenewCorpoEmpPlan: `/api/${version}/admin/corpoEmp/plan-renew`,
  RenewBulkCorpoEmpPlan: `/api/${version}/admin/corpoEmp/plan-renew-bulk`,
  GetFailedBulkUpload: `/api/${version}/admin/corpoEmp/failedRecordsInserts/`,
  DeleteFailedBulkUpload: `/api/${version}/admin/corpoEmp/deleteFailedRecordsInserts/`,
  GetAdminUserProfile : `/api/${version}/admin/get-profile/`,
  GetAllConditions: `/api/${version}/admin/conditions/`,
  EditCondition: `/api/${version}/admin/conditions/`,
  GetAllCorpoEmp: `/api/${version}/admin/corpoEmp/`,
  GetCorpoEmp: `/api/${version}/admin/allcorpoEmp/`,
  EditCorpoEmp: `/api/${version}/admin/corpoEmp/`,
  EditCorpoEmpPassword: `/api/${version}/admin/corpoEmp/password/`,
  DeleteCorpoEmpAdmin: `/api/${version}/admin/corpoEmp/`,
  AddCorpoEmp: `/api/${version}/admin/corpoEmp/`,
  GetAllManUsers: `/api/${version}/admin/managmentUser/`,
  EditManUsers: `/api/${version}/admin/managmentUser/details/`,
  EditManUsersPass: `/api/${version}/admin/managmentUser/password/`,
  DeleteManUsers: `/api/${version}/admin/managmentUser/`,
  AddManUsers: `/api/${version}/admin/managmentUser/`,
  GetAllCoupons: `/api/${version}/admin/coupon/`,
  GetAllCouponsList: `/api/${version}/admin/couponlist/`,
  EditCoupon: `/api/${version}/admin/coupon/`,
  DeleteCoupon: `/api/${version}/admin/coupon/`,
  AddCoupon: `/api/${version}/admin/coupon/`,
  GetAllDoctors: `/api/${version}/admin/doctor/`,
  GetAllDoctorsList: `/api/${version}/admin/doctorlist/`,
  GetDoctorsFromClaims: `/api/${version}/admin/doctorfromclaims/`,
  GetDoctorsFromClaimsList: `/api/${version}/admin/doctorfromclaimslist/`,
  GetDoctorsFromClaimsDetails: `/api/${version}/admin/get-doctorfromclaims-details/`,
  EditDoctor: `/api/${version}/admin/doctor/`,
  DeleteDoctor: `/api/${version}/admin/doctor/`,
  AddDoctor: `/api/${version}/admin/doctor/`,
  GetAdminProgList: `/api/${version}/admin/programs/admin`,
  GetGeneralProgList: `/api/${version}/admin/programs/general`,
  GetAllPrivilegs: `/api/${version}/admin/privilege/`,
  GetIndividualPrivilegs: `/api/${version}/admin/privilege/`,
  EditPrivilegs: `/api/${version}/admin/privilege/`,
  AddPrivilegs: `/api/${version}/admin/privilege/`,
  GetAllAdminUsers: `/api/${version}/admin/adminUsers/details`,
  GetAllAdminAuditLogs: `/api/${version}/admin/auditTrail/adminUsers`,
  GetAllGeneralUsersAuditLogs: `/api/${version}/admin/auditTrail/generalUsers`,

  HrLogin: `/api/${version}/hr/login`,
  HrLogout: `/api/${version}/hr/logout`,
  HrAddCorpoEmp: `/api/${version}/hr/corpoEmp/`,
  HrAddCorpoEmpBulk: `/api/${version}/hr/corpoEmp/bulk`,
  HrGetAllCorpoEmp: `/api/${version}/hr/corpoEmp/`,
  HrEditCorpoEmp: `/api/${version}/hr/corpoEmp/`,
  DeleteCorpoEmp: `/api/${version}/hr/corpoEmp/`,
  HrEditCorpoEmpPass: `/api/${version}/hr/corpoEmp/password/`,
  HrGetFailedCorpoInserts: `/api/${version}/hr/corpoEmp/failedRecordsInserts/`,
  HrDeleteFailedCorpoInserts: `/api/${version}/hr/corpoEmp/deleteFailedRecordsInserts/`,


  ContactUsCorporate: `/api/${version}/public/contact-us-corporate/`,
  ContactUsRetail: `/api/${version}/public/contact-us-retail/`,
  ContactUsEmail : `/api/${version}/public/contact-us-email/`,

  GetAllFAQs: `/api/${version}/public/FAQs`,
  AddFAQs: `/api/${version}/admin/FAQs`,
  EditFAQs: `/api/${version}/admin/FAQs`,
  DeleteFAQs: `/api/${version}/admin/FAQs`

};
export default config;
